/*
 * 既有資料庫的基準（baseline）migration。
 *
 * 內容取自 2026-09-10 對正式環境執行的
 * `supabase db dump --schema public`，
 * 目的是讓新環境能重建出相同結構。
 *
 * 所有敘述都寫成可重複執行的形式，
 * 對已經有這些物件的資料庫執行也不會出錯。
 */

begin;

/*
 * 章節閱讀權限。
 *
 * 只有 confirm_newebpay_payment() 會寫入，
 * 所以這裡不開放任何 INSERT / UPDATE / DELETE policy。
 */
create table if not exists public.chapter_access (
    id bigint
        generated by default as identity
        primary key,

    user_id uuid not null
        references auth.users(id) on delete cascade,

    book_slug text not null,
    chapter_slug text not null,

    created_at timestamptz not null default now(),

    unique (user_id, book_slug, chapter_slug)
);

/*
 * 付費章節正文。
 *
 * 正文不放在 content/ 的 Markdown 裡，
 * 只靠下面的 SELECT policy 擋住未購買的會員。
 */
create table if not exists public.paid_chapter_content (
    id bigint
        generated by default as identity
        primary key,

    book_slug text not null,
    chapter_slug text not null,

    body text not null,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    unique (book_slug, chapter_slug)
);

/*
 * 訂單。
 *
 * status 目前使用：
 * pending / paid / failed / cancelled / refunded。
 */
create table if not exists public.orders (
    id bigint
        generated by default as identity
        primary key,

    user_id uuid not null
        references auth.users(id) on delete cascade,

    order_no text not null unique,

    book_slug text not null,
    chapter_slug text not null,

    amount integer not null,
    currency text not null default 'TWD',
    status text not null default 'pending',

    payment_provider text,
    provider_payment_id text,

    created_at timestamptz not null default now(),
    paid_at timestamptz
);

/*
 * 雲端閱讀進度。
 *
 * 每位會員每本書只保留一筆，
 * 對應 useReadingProgress 的 onConflict: 'user_id,book_slug'。
 */
create table if not exists public.reading_progress (
    id bigint
        generated by default as identity
        primary key,

    user_id uuid not null
        references auth.users(id) on delete cascade,

    book_slug text not null,
    chapter_slug text not null,

    progress integer not null default 0,

    updated_at timestamptz not null default now(),

    unique (user_id, book_slug)
);

alter table public.chapter_access
    enable row level security;

alter table public.paid_chapter_content
    enable row level security;

alter table public.orders
    enable row level security;

alter table public.reading_progress
    enable row level security;

/*
 * Policy 一律先 drop 再 create，
 * 讓這份檔案可以重複執行。
 */
drop policy if exists "Users can read own chapter access"
    on public.chapter_access;

create policy "Users can read own chapter access"
    on public.chapter_access
    for select
    to authenticated
    using (auth.uid() = user_id);

/*
 * 未購買者連正文都查不到，
 * 這條 policy 是付費內容的唯一防線。
 */
drop policy if exists "Users can read purchased chapter content"
    on public.paid_chapter_content;

create policy "Users can read purchased chapter content"
    on public.paid_chapter_content
    for select
    to authenticated
    using (
        exists (
            select 1
            from public.chapter_access
            where chapter_access.user_id = auth.uid()
              and chapter_access.book_slug = paid_chapter_content.book_slug
              and chapter_access.chapter_slug = paid_chapter_content.chapter_slug
        )
    );

/*
 * 訂單只能讀，不能由 Browser 建立或修改。
 * 建立走 /api/payments/create，狀態變更走藍新通知。
 */
drop policy if exists "Users can read own orders"
    on public.orders;

create policy "Users can read own orders"
    on public.orders
    for select
    to authenticated
    using (auth.uid() = user_id);

drop policy if exists "Users can read own reading progress"
    on public.reading_progress;

create policy "Users can read own reading progress"
    on public.reading_progress
    for select
    to authenticated
    using (auth.uid() = user_id);

drop policy if exists "Users can insert own reading progress"
    on public.reading_progress;

create policy "Users can insert own reading progress"
    on public.reading_progress
    for insert
    to authenticated
    with check (auth.uid() = user_id);

drop policy if exists "Users can update own reading progress"
    on public.reading_progress;

create policy "Users can update own reading progress"
    on public.reading_progress
    for update
    to authenticated
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

/*
 * 這些 grant 是 Supabase 專案的預設值，
 * 實際的存取控制由上面的 RLS policy 負責。
 */
grant all on table public.chapter_access
    to anon, authenticated, service_role;

grant all on table public.paid_chapter_content
    to anon, authenticated, service_role;

grant all on table public.orders
    to anon, authenticated, service_role;

grant all on table public.reading_progress
    to anon, authenticated, service_role;

grant all on sequence public.chapter_access_id_seq
    to anon, authenticated, service_role;

grant all on sequence public.paid_chapter_content_id_seq
    to anon, authenticated, service_role;

grant all on sequence public.orders_id_seq
    to anon, authenticated, service_role;

grant all on sequence public.reading_progress_id_seq
    to anon, authenticated, service_role;

commit;
