BEGIN;

/*
 * 讀者問題回報。
 *
 * 只能透過 /api/support/reports 建立（service_role），
 * 前端沒有任何讀寫權限。
 */
CREATE TABLE public.support_reports (
                                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                        report_no text NOT NULL UNIQUE
                                            CHECK (report_no ~ '^RP[0-9]{8}-[0-9A-F]{6}$'),

    user_id uuid NOT NULL
        REFERENCES auth.users(id) ON DELETE CASCADE,

    category text NOT NULL
        CHECK (category IN ('content', 'reading', 'paid_unreadable', 'other')),

    description text NOT NULL
        CHECK (char_length(description) BETWEEN 10 AND 2000),

    contact_email text NOT NULL
        CHECK (char_length(contact_email) BETWEEN 3 AND 254),

    book_slug text
        CHECK (book_slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),

    chapter_slug text
        CHECK (chapter_slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),

    order_no text
        CHECK (order_no ~ '^[A-Za-z0-9]{1,30}$'),

    user_agent text NOT NULL DEFAULT ''
        CHECK (char_length(user_agent) <= 300),

    status text NOT NULL DEFAULT 'open'
        CHECK (status IN ('open', 'in_progress', 'resolved', 'closed')),

    admin_note text NOT NULL DEFAULT '',

    created_at timestamptz NOT NULL DEFAULT now(),
    resolved_at timestamptz,

    -- 有章節就一定要有書。
    CHECK (chapter_slug IS NULL OR book_slug IS NOT NULL)
);

-- 頻率限制與重複檢查都靠這個索引。
CREATE INDEX support_reports_user_created_idx
    ON public.support_reports (user_id, created_at DESC);

-- 查看待處理回報時用。
CREATE INDEX support_reports_open_idx
    ON public.support_reports (created_at DESC)
    WHERE status IN ('open', 'in_progress');

ALTER TABLE public.support_reports
    ENABLE ROW LEVEL SECURITY;

/*
 * 目前前端不讀取回報，所以不開放權限給 anon / authenticated。
 * 這條 policy 先寫好：之後做「我的回報」時只要開放欄位權限，
 * 會員就只看得到自己的資料。
 */
CREATE POLICY "Users can read own support reports"
    ON public.support_reports
    FOR SELECT
                   TO authenticated
                   USING ((SELECT auth.uid()) = user_id);

-- Supabase 會自動把新表的權限給 anon / authenticated，必須收回。
REVOKE ALL ON TABLE public.support_reports
    FROM PUBLIC, anon, authenticated;

REVOKE ALL ON SEQUENCE public.support_reports_id_seq
    FROM PUBLIC, anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLE public.support_reports
    TO service_role;

GRANT USAGE, SELECT
    ON SEQUENCE public.support_reports_id_seq
    TO service_role;

/*
 * 建立回報：重複檢查、頻率限制與寫入在同一個交易內完成。
 *
 * 輸出欄位刻意不叫 report_no，
 * 避免在 PL/pgSQL 裡跟資料表欄位同名而產生歧義。
 */
CREATE FUNCTION public.create_support_report(
    p_user_id uuid,
    p_category text,
    p_description text,
    p_contact_email text,
    p_book_slug text,
    p_chapter_slug text,
    p_order_no text,
    p_user_agent text
)
    RETURNS TABLE (report_number text, is_duplicate boolean)
    LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
v_now timestamptz := clock_timestamp();
  v_existing text;
  v_report_no text;
  v_attempt integer := 0;
BEGIN
  IF p_user_id IS NULL THEN
    RAISE EXCEPTION 'User ID is required';
END IF;

  -- 同一會員依序處理，連點兩次也不會同時通過檢查。
  PERFORM pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('support-report:' || p_user_id::text, 0)
  );

  -- 10 分鐘內送出完全相同的內容，直接回傳原本的編號。
SELECT r.report_no
INTO v_existing
FROM public.support_reports AS r
WHERE r.user_id = p_user_id
  AND r.category = p_category
  AND r.description = p_description
  AND r.book_slug IS NOT DISTINCT FROM p_book_slug
    AND r.chapter_slug IS NOT DISTINCT FROM p_chapter_slug
    AND r.order_no IS NOT DISTINCT FROM p_order_no
    AND r.created_at > v_now - interval '10 minutes'
ORDER BY r.created_at DESC
    LIMIT 1;

IF FOUND THEN
    RETURN QUERY SELECT v_existing, true;
RETURN;
END IF;

  -- 冷卻：距離上一筆回報不到 60 秒。
  IF EXISTS (
    SELECT 1
    FROM public.support_reports AS r
    WHERE r.user_id = p_user_id
      AND r.created_at > v_now - interval '60 seconds'
  ) THEN
    RAISE EXCEPTION 'support_report_cooldown';
END IF;

  -- 上限：24 小時內最多 10 筆。
  IF (
SELECT count(*)
FROM public.support_reports AS r
WHERE r.user_id = p_user_id
  AND r.created_at > v_now - interval '24 hours'
    ) >= 10 THEN
    RAISE EXCEPTION 'support_report_daily_limit';
END IF;

  LOOP
v_attempt := v_attempt + 1;

    -- 例：RP20260911-4F9A2C
    v_report_no := 'RP'
      || pg_catalog.to_char(v_now AT TIME ZONE 'Asia/Taipei', 'YYYYMMDD')
      || '-'
      || pg_catalog.upper(
           pg_catalog.substr(
             pg_catalog.md5(pg_catalog.gen_random_uuid()::text),
             1,
             6
           )
         );

BEGIN
INSERT INTO public.support_reports (
    report_no,
    user_id,
    category,
    description,
    contact_email,
    book_slug,
    chapter_slug,
    order_no,
    user_agent
)
VALUES (
           v_report_no,
           p_user_id,
           p_category,
           p_description,
           p_contact_email,
           p_book_slug,
           p_chapter_slug,
           p_order_no,
           p_user_agent
       );

EXIT;
EXCEPTION
      WHEN unique_violation THEN
        -- 編號碰撞的機率極低，重試 5 次仍失敗才往上丟。
        IF v_attempt >= 5 THEN
          RAISE;
END IF;
END;
END LOOP;

RETURN QUERY SELECT v_report_no, false;
END;
$$;

REVOKE EXECUTE
    ON FUNCTION public.create_support_report(
    uuid, text, text, text, text, text, text, text
    )
    FROM PUBLIC, anon, authenticated;

GRANT EXECUTE
ON FUNCTION public.create_support_report(
        uuid, text, text, text, text, text, text, text
    )
    TO service_role;

COMMIT;